// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OrdersAsyncContract
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Order : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Order"",""namespace"":""OrdersAsyncContract"",""fields"":[{""name"":""Id"",""type"":""int""},{""name"":""Dishes"",""type"":{""type"":""array"",""items"":""string""}},{""name"":""TotalCost"",""type"":""double""},{""name"":""CreatedAt"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}}]}");
		private int _Id;
		private IList<System.String> _Dishes;
		private double _TotalCost;
		private System.DateTime _CreatedAt;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Order._SCHEMA;
			}
		}
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public IList<System.String> Dishes
		{
			get
			{
				return this._Dishes;
			}
			set
			{
				this._Dishes = value;
			}
		}
		public double TotalCost
		{
			get
			{
				return this._TotalCost;
			}
			set
			{
				this._TotalCost = value;
			}
		}
		public System.DateTime CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				this._CreatedAt = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Dishes;
			case 2: return this.TotalCost;
			case 3: return this.CreatedAt;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int32)fieldValue; break;
			case 1: this.Dishes = (IList<System.String>)fieldValue; break;
			case 2: this.TotalCost = (System.Double)fieldValue; break;
			case 3: this.CreatedAt = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
